#!/usr/bin/env bash
set -euo pipefail

PROFILE="tgx-admin"
ACCOUNT_ID="419130719494"
REGION="us-west-2"
BUCKET="tgx-prod-media-419130719494"
MEDIA_DOMAIN="media.turbogixxertuning.com"
HOSTED_ZONE_NAME="turbogixxertuning.com"
DOC_FILE="docs/media-url-map.md"
PREFIXES=("brand/" "gallery/" "services/" "products/" "videos/" "pdfs/")

failures=0
sample_key=""
cloudfront_id=""
cloudfront_domain=""

info() {
  printf "\n==> %s\n" "$1"
}

pass() {
  printf "OK: %s\n" "$1"
}

fail() {
  printf "FAIL: %s\n" "$1" >&2
  failures=$((failures + 1))
}

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "Required command not found: $1"
    return 1
  fi
}

aws_cli() {
  aws --profile "$PROFILE" "$@"
}

json_array_to_lines() {
  python3 -c 'import json, sys; data = json.load(sys.stdin) or []; data = [key for key in data if not key.endswith("/.keep") and not key.endswith(".keep")]; print("\n".join(data))'
}

url_encode_path() {
  python3 - "$1" <<'PY'
import sys
import urllib.parse

print(urllib.parse.quote(sys.argv[1], safe="/-_.~"))
PY
}

get_hosted_zone_id() {
  aws_cli route53 list-hosted-zones-by-name \
    --dns-name "${HOSTED_ZONE_NAME}." \
    --query "HostedZones[?Name=='${HOSTED_ZONE_NAME}.' && Config.PrivateZone==\`false\`].Id | [0]" \
    --output text
}

write_media_url_map() {
  local tmp_file
  tmp_file="$(mktemp)"

  {
    printf "# Media URL Map\n\n"
    printf "Generated by \`scripts/verify-media-cdn.sh\` from objects found in \`s3://%s\`.\n\n" "$BUCKET"
    printf "Base URL:\n\n"
    printf "\`\`\`txt\n"
    printf "https://%s\n" "$MEDIA_DOMAIN"
    printf "\`\`\`\n\n"
    printf "Frontend environment variable:\n\n"
    printf "\`\`\`txt\n"
    printf "NEXT_PUBLIC_MEDIA_BASE_URL=https://%s\n" "$MEDIA_DOMAIN"
    printf "\`\`\`\n\n"
    printf "Example URL format:\n\n"
    printf "%s\n" "- https://${MEDIA_DOMAIN}/services/featuredbuild-01.webp"
    printf "%s\n\n" "- https://${MEDIA_DOMAIN}/gallery/blue-c10-lowered.png"

    for prefix in "${PREFIXES[@]}"; do
      local keys
      printf "## %s\n\n" "${prefix%/}"

      if ! keys="$(aws_cli s3api list-objects-v2 \
        --bucket "$BUCKET" \
        --prefix "$prefix" \
        --query 'Contents[?Size > `0`].Key' \
        --output json | json_array_to_lines)"; then
        printf "_Unable to list this prefix._\n\n"
        continue
      fi

      if [[ -z "$keys" ]]; then
        printf "_No files found under \`%s\`._\n\n" "$prefix"
        continue
      fi

      printf "| S3 key | CDN URL |\n"
      printf "| --- | --- |\n"

      while IFS= read -r key; do
        [[ -z "$key" ]] && continue
        local encoded_key
        encoded_key="$(url_encode_path "$key")"
        printf "| \`%s\` | https://%s/%s |\n" "$key" "$MEDIA_DOMAIN" "$encoded_key"
      done <<< "$keys"

      printf "\n"
    done
  } > "$tmp_file"

  python3 - "$tmp_file" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
path.write_text(path.read_text(encoding="utf-8").rstrip() + "\n", encoding="utf-8")
PY

  mv "$tmp_file" "$DOC_FILE"
  pass "Generated $DOC_FILE"
}

parse_cloudfront_distribution() {
  local json_file="$1"

  python3 - "$json_file" "$MEDIA_DOMAIN" "$BUCKET" <<'PY'
import json
import sys

json_file, media_domain, bucket = sys.argv[1:4]

with open(json_file, "r", encoding="utf-8") as handle:
    data = json.load(handle)

items = data.get("DistributionList", {}).get("Items", []) or []
found = None

for distribution in items:
    aliases = distribution.get("Aliases", {}).get("Items", []) or []
    if media_domain in aliases:
        found = distribution
        break

if not found:
    print("||no|no|")
    raise SystemExit(0)

origins = found.get("Origins", {}).get("Items", []) or []
origin_domains = [origin.get("DomainName", "") for origin in origins]
origin_match = any(bucket in domain for domain in origin_domains)

fields = [
    found.get("Id", ""),
    found.get("DomainName", ""),
    "yes",
    "yes" if origin_match else "no",
    ",".join(origin_domains),
]

print("|".join(fields))
PY
}

parse_route53_aliases() {
  local json_file="$1"
  local expected_cloudfront_domain="$2"

  python3 - "$json_file" "$MEDIA_DOMAIN" "$expected_cloudfront_domain" <<'PY'
import json
import sys

json_file, media_domain, expected_domain = sys.argv[1:4]
expected_domain = expected_domain.rstrip(".")

with open(json_file, "r", encoding="utf-8") as handle:
    data = json.load(handle)

records = data.get("ResourceRecordSets", []) or []
name = f"{media_domain}."
result = {}

def normalized_target(value):
    value = (value or "").rstrip(".")
    if value.startswith("dualstack."):
        value = value[len("dualstack."):]
    return value

for record_type in ("A", "AAAA"):
    target = ""
    hosted_zone_id = ""
    for record in records:
        if record.get("Name") == name and record.get("Type") == record_type:
            alias = record.get("AliasTarget", {}) or {}
            target = alias.get("DNSName", "")
            hosted_zone_id = alias.get("HostedZoneId", "")
            break

    normalized = normalized_target(target)
    matches = bool(expected_domain) and normalized == expected_domain
    result[record_type] = (target, hosted_zone_id, "yes" if matches else "no")

print("|".join([
    result["A"][0],
    result["A"][1],
    result["A"][2],
    result["AAAA"][0],
    result["AAAA"][1],
    result["AAAA"][2],
]))
PY
}

info "Checking local tools"
need_cmd aws || true
need_cmd python3 || true
need_cmd curl || true

if [[ "$failures" -gt 0 ]]; then
  printf "\nVerification cannot continue until required local commands are installed.\n" >&2
  exit 1
fi

info "Verifying AWS account"
if account="$(aws_cli sts get-caller-identity --query Account --output text 2>/dev/null)"; then
  if [[ "$account" == "$ACCOUNT_ID" ]]; then
    pass "AWS profile $PROFILE is using account $ACCOUNT_ID"
  else
    fail "AWS profile $PROFILE is using account $account, expected $ACCOUNT_ID"
  fi
else
  fail "Could not read caller identity. Run: aws sso login --profile $PROFILE"
fi

info "Checking S3 bucket"
bucket_exists="no"
if aws_cli s3api head-bucket --bucket "$BUCKET" --region "$REGION" >/dev/null 2>&1; then
  bucket_exists="yes"
  pass "S3 bucket exists: s3://$BUCKET"
else
  fail "S3 bucket does not exist or is not accessible: s3://$BUCKET"
fi

if [[ "$bucket_exists" == "yes" ]]; then
  info "Listing media prefixes"
  for prefix in "${PREFIXES[@]}"; do
    printf "\n%s\n" "$prefix"

    if keys="$(aws_cli s3api list-objects-v2 \
      --bucket "$BUCKET" \
      --prefix "$prefix" \
      --query 'Contents[?Size > `0`].Key' \
      --output json | json_array_to_lines)"; then
      if [[ -z "$keys" ]]; then
        printf "  No files found.\n"
        continue
      fi

      count=0
      while IFS= read -r key; do
        [[ -z "$key" ]] && continue
        if [[ -z "$sample_key" ]]; then
          sample_key="$key"
        fi
        count=$((count + 1))
        if [[ "$count" -le 5 ]]; then
          printf "  %s\n" "$key"
        fi
      done <<< "$keys"

      if [[ "$count" -gt 5 ]]; then
        printf "  ...and %s more\n" "$((count - 5))"
      fi
    else
      fail "Could not list prefix: s3://$BUCKET/$prefix"
    fi
  done

  write_media_url_map
fi

info "Checking CloudFront distribution"
cf_tmp="$(mktemp)"
if aws_cli cloudfront list-distributions --output json > "$cf_tmp"; then
  cf_result="$(parse_cloudfront_distribution "$cf_tmp")"
  IFS='|' read -r cloudfront_id cloudfront_domain alias_match origin_match origin_domains <<< "$cf_result"

  if [[ -n "$cloudfront_id" ]]; then
    pass "CloudFront distribution found: $cloudfront_id ($cloudfront_domain)"

    if [[ "$alias_match" == "yes" ]]; then
      pass "CloudFront alias includes $MEDIA_DOMAIN"
    else
      fail "CloudFront alias does not include $MEDIA_DOMAIN"
    fi

    if [[ "$origin_match" == "yes" ]]; then
      pass "CloudFront origin points to $BUCKET"
    else
      fail "CloudFront origin does not point to $BUCKET. Origins: $origin_domains"
    fi
  else
    fail "No CloudFront distribution found with alias $MEDIA_DOMAIN"
  fi
else
  fail "Could not list CloudFront distributions"
fi
rm -f "$cf_tmp"

info "Checking Route 53 alias records"
zone_id="$(get_hosted_zone_id || true)"
if [[ -z "$zone_id" || "$zone_id" == "None" ]]; then
  fail "Could not find public Route 53 hosted zone: $HOSTED_ZONE_NAME"
else
  zone_id="${zone_id#/hostedzone/}"
  pass "Route 53 hosted zone found: $zone_id"

  r53_tmp="$(mktemp)"
  if aws_cli route53 list-resource-record-sets --hosted-zone-id "$zone_id" --output json > "$r53_tmp"; then
    r53_result="$(parse_route53_aliases "$r53_tmp" "$cloudfront_domain")"
    IFS='|' read -r a_target a_zone a_match aaaa_target aaaa_zone aaaa_match <<< "$r53_result"

    if [[ -n "$a_target" ]]; then
      printf "A alias target: %s\n" "$a_target"
      if [[ "$a_match" == "yes" ]]; then
        pass "Route 53 A record points to CloudFront distribution $cloudfront_domain"
      else
        fail "Route 53 A record does not point to CloudFront distribution $cloudfront_domain"
      fi
    else
      fail "Route 53 A alias record is missing for $MEDIA_DOMAIN"
    fi

    if [[ -n "$aaaa_target" ]]; then
      printf "AAAA alias target: %s\n" "$aaaa_target"
      if [[ "$aaaa_match" == "yes" ]]; then
        pass "Route 53 AAAA record points to CloudFront distribution $cloudfront_domain"
      else
        fail "Route 53 AAAA record does not point to CloudFront distribution $cloudfront_domain"
      fi
    else
      fail "Route 53 AAAA alias record is missing for $MEDIA_DOMAIN"
    fi
  else
    fail "Could not list Route 53 records for hosted zone $zone_id"
  fi
  rm -f "${r53_tmp:-}"
fi

info "Testing media delivery"
if [[ -z "$sample_key" ]]; then
  fail "No sample object found in S3 prefixes; cannot test CDN or raw S3 URL"
else
  encoded_key="$(url_encode_path "$sample_key")"
  cdn_url="https://${MEDIA_DOMAIN}/${encoded_key}"
  raw_s3_url="https://${BUCKET}.s3.${REGION}.amazonaws.com/${encoded_key}"

  printf "Sample object: %s\n" "$sample_key"
  printf "CloudFront URL: %s\n" "$cdn_url"
  cdn_status="$(curl -L -sS -o /dev/null -w "%{http_code}" "$cdn_url" || true)"
  if [[ "$cdn_status" == "200" ]]; then
    pass "CloudFront returned 200 for sample media URL"
  else
    fail "CloudFront returned HTTP $cdn_status for $cdn_url"
  fi

  printf "Raw S3 URL: %s\n" "$raw_s3_url"
  s3_status="$(curl -sS -o /dev/null -w "%{http_code}" "$raw_s3_url" || true)"
  if [[ "$s3_status" == "403" ]]; then
    pass "Raw S3 URL is blocked with HTTP 403"
  else
    fail "Raw S3 URL returned HTTP $s3_status; expected 403"
  fi
fi

if [[ "$failures" -gt 0 ]]; then
  printf "\nVerification failed with %s issue(s).\n" "$failures" >&2
  printf "If the CDN is not set up yet, run: ./scripts/setup-media-cdn.sh\n" >&2
  exit 1
fi

printf "\nVerification succeeded. Media CDN is ready.\n"
